<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('municipalities', function (Blueprint $table) {
            $table->smallInteger('id')->autoIncrement()->unsigned();
            $table->string('name', 50);
            $table->tinyInteger('departmentIdFK')->unsigned();
        });


        DB::table('municipalities')->insert(
            [
                ['name' => 'La Ceiba', 'departmentIdFK' => 1],
                ['name' => 'El Porvenir', 'departmentIdFK' => 1],
                ['name' => 'Esparta', 'departmentIdFK' => 1],
                ['name' => 'Jutiapa', 'departmentIdFK' => 1],
                ['name' => 'La Masica', 'departmentIdFK' => 1],
                ['name' => 'San Francisco', 'departmentIdFK' => 1],
                ['name' => 'Tela', 'departmentIdFK' => 1],
                ['name' => 'Arizona', 'departmentIdFK' => 1],
                ['name' => 'Trujillo', 'departmentIdFK' => 2],
                ['name' => 'Balfate', 'departmentIdFK' => 2],
                ['name' => 'Iriona', 'departmentIdFK' => 2],
                ['name' => 'Limon', 'departmentIdFK' => 2],
                ['name' => 'Saba', 'departmentIdFK' => 2],
                ['name' => 'Santa Fe', 'departmentIdFK' => 2],
                ['name' => 'Santa Rosa de Aguan', 'departmentIdFK' => 2],
                ['name' => 'Tocoa', 'departmentIdFK' => 2],
                ['name' => 'Bonito Oriental', 'departmentIdFK' => 2],
                ['name' => 'Comayagua', 'departmentIdFK' => 3],
                ['name' => 'Ajuterique', 'departmentIdFK' => 3],
                ['name' => 'El Rosario', 'departmentIdFK' => 3],
                ['name' => 'Esquias', 'departmentIdFK' => 3],
                ['name' => 'Humuya', 'departmentIdFK' => 3],
                ['name' => 'La Libertad', 'departmentIdFK' => 3],
                ['name' => 'Lamani', 'departmentIdFK' => 3],
                ['name' => 'La Trinidad', 'departmentIdFK' => 3],
                ['name' => 'Lejamani', 'departmentIdFK' => 3],
                ['name' => 'Meambar', 'departmentIdFK' => 3],
                ['name' => 'Minas de Oro', 'departmentIdFK' => 3],
                ['name' => 'Ojos de Agua', 'departmentIdFK' => 3],
                ['name' => 'San Jerónimo', 'departmentIdFK' => 3],
                ['name' => 'San Jose de Comayagua', 'departmentIdFK' => 3],
                ['name' => 'San Jose del Potrero', 'departmentIdFK' => 3],
                ['name' => 'San Luis', 'departmentIdFK' => 3],
                ['name' => 'San Sebastian', 'departmentIdFK' => 3],
                ['name' => 'Siguatepeque', 'departmentIdFK' => 3],
                ['name' => 'Villa de San Antonio', 'departmentIdFK' => 3],
                ['name' => 'Las Lajas', 'departmentIdFK' => 3],
                ['name' => 'Taulabe', 'departmentIdFK' => 3],
                ['name' => 'Santa Rosa de Copan', 'departmentIdFK' => 4],
                ['name' => 'Cabana', 'departmentIdFK' => 4],
                ['name' => 'Concepción', 'departmentIdFK' => 4],
                ['name' => 'Copan Ruinas', 'departmentIdFK' => 4],
                ['name' => 'Corquin', 'departmentIdFK' => 4],
                ['name' => 'Cucuyagua', 'departmentIdFK' => 4],
                ['name' => 'Dolores', 'departmentIdFK' => 4],
                ['name' => 'Dulce Nombre', 'departmentIdFK' => 4],
                ['name' => 'El Paraiso', 'departmentIdFK' => 4],
                ['name' => 'Florida', 'departmentIdFK' => 4],
                ['name' => 'La Jigua', 'departmentIdFK' => 4],
                ['name' => 'La Union', 'departmentIdFK' => 4],
                ['name' => 'Nueva Arcadia', 'departmentIdFK' => 4],
                ['name' => 'San Agustin', 'departmentIdFK' => 4],
                ['name' => 'San Antonio', 'departmentIdFK' => 4],
                ['name' => 'San Jeronimo', 'departmentIdFK' => 4],
                ['name' => 'San Jose', 'departmentIdFK' => 4],
                ['name' => 'San Juan de Opoa', 'departmentIdFK' => 4],
                ['name' => 'San Nicolas', 'departmentIdFK' => 4],
                ['name' => 'San Pedro', 'departmentIdFK' => 4],
                ['name' => 'Santa Rita', 'departmentIdFK' => 4],
                ['name' => 'Trinidad de Copan', 'departmentIdFK' => 4],
                ['name' => 'Veracruz', 'departmentIdFK' => 4],
                ['name' => 'San Pedro Sula', 'departmentIdFK' => 5],
                ['name' => 'Choloma', 'departmentIdFK' => 5],
                ['name' => 'Omoa', 'departmentIdFK' => 5],
                ['name' => 'Pimienta', 'departmentIdFK' => 5],
                ['name' => 'Potrerillos', 'departmentIdFK' => 5],
                ['name' => 'Puerto Cortes', 'departmentIdFK' => 5],
                ['name' => 'San Antonio de Cortes', 'departmentIdFK' => 5],
                ['name' => 'San Francisco de Yojoa', 'departmentIdFK' => 5],
                ['name' => 'San Manuel', 'departmentIdFK' => 5],
                ['name' => 'Santa Cruz de Yojoa', 'departmentIdFK' => 5],
                ['name' => 'Villanueva', 'departmentIdFK' => 5],
                ['name' => 'La Lima', 'departmentIdFK' => 5],
                ['name' => 'Choluteca', 'departmentIdFK' => 6],
                ['name' => 'Apacilagua', 'departmentIdFK' => 6],
                ['name' => 'Concepcion de Maria', 'departmentIdFK' => 6],
                ['name' => 'Duyure', 'departmentIdFK' => 6],
                ['name' => 'El Corpus', 'departmentIdFK' => 6],
                ['name' => 'El Triunfo', 'departmentIdFK' => 6],
                ['name' => 'Marcovia', 'departmentIdFK' => 6],
                ['name' => 'Morolica', 'departmentIdFK' => 6],
                ['name' => 'Namasigue', 'departmentIdFK' => 6],
                ['name' => 'Orocuina', 'departmentIdFK' => 6],
                ['name' => 'Pespire', 'departmentIdFK' => 6],
                ['name' => 'San Antonio de Flores', 'departmentIdFK' => 6],
                ['name' => 'San Isidro', 'departmentIdFK' => 6],
                ['name' => 'San Jose', 'departmentIdFK' => 6],
                ['name' => 'San Marcos de Colon', 'departmentIdFK' => 6],
                ['name' => 'Santa Ana de Yusguare', 'departmentIdFK' => 6],
                ['name' => 'Yuscaran', 'departmentIdFK' => 7],
                ['name' => 'Alauca', 'departmentIdFK' => 7],
                ['name' => 'Danli', 'departmentIdFK' => 7],
                ['name' => 'El Paraiso', 'departmentIdFK' => 7],
                ['name' => 'Guinope', 'departmentIdFK' => 7],
                ['name' => 'Jacaleapa', 'departmentIdFK' => 7],
                ['name' => 'Liure', 'departmentIdFK' => 7],
                ['name' => 'Moroceli', 'departmentIdFK' => 7],
                ['name' => 'Oropoli', 'departmentIdFK' => 7],
                ['name' => 'Potrerillos', 'departmentIdFK' => 7],
                ['name' => 'San Antonio de Flores', 'departmentIdFK' => 7],
                ['name' => 'San Lucas', 'departmentIdFK' => 7],
                ['name' => 'San Matias', 'departmentIdFK' => 7],
                ['name' => 'Soledad', 'departmentIdFK' => 7],
                ['name' => 'Teupasenti', 'departmentIdFK' => 7],
                ['name' => 'Texiguat', 'departmentIdFK' => 7],
                ['name' => 'Vado Ancho', 'departmentIdFK' => 7],
                ['name' => 'Yauyupe', 'departmentIdFK' => 7],
                ['name' => 'Trojes', 'departmentIdFK' => 7],
                ['name' => 'Distrito Central', 'departmentIdFK' => 8],
                ['name' => 'Alubaren', 'departmentIdFK' => 8],
                ['name' => 'Cedros', 'departmentIdFK' => 8],
                ['name' => 'Curaren', 'departmentIdFK' => 8],
                ['name' => 'El Porvenir', 'departmentIdFK' => 8],
                ['name' => 'Guaimaca', 'departmentIdFK' => 8],
                ['name' => 'La Libertad', 'departmentIdFK' => 8],
                ['name' => 'La Venta', 'departmentIdFK' => 8],
                ['name' => 'Lepaterique', 'departmentIdFK' => 8],
                ['name' => 'Maraita', 'departmentIdFK' => 8],
                ['name' => 'Marale', 'departmentIdFK' => 8],
                ['name' => 'Nueva Armenia', 'departmentIdFK' => 8],
                ['name' => 'Ojojona', 'departmentIdFK' => 8],
                ['name' => 'Orica', 'departmentIdFK' => 8],
                ['name' => 'Reitoca', 'departmentIdFK' => 8],
                ['name' => 'Sabanagrande', 'departmentIdFK' => 8],
                ['name' => 'San Antonio de Oriente', 'departmentIdFK' => 8],
                ['name' => 'San Buenaventura', 'departmentIdFK' => 8],
                ['name' => 'San Ignacio', 'departmentIdFK' => 8],
                ['name' => 'San Juan de Flores', 'departmentIdFK' => 8],
                ['name' => 'San Miguelito', 'departmentIdFK' => 8],
                ['name' => 'Santa Ana', 'departmentIdFK' => 8],
                ['name' => 'Santa Lucia', 'departmentIdFK' => 8],
                ['name' => 'Talanga', 'departmentIdFK' => 8],
                ['name' => 'Tatumbla', 'departmentIdFK' => 8],
                ['name' => 'Valle de Angeles', 'departmentIdFK' => 8],
                ['name' => 'Villa de San Francisco', 'departmentIdFK' => 8],
                ['name' => 'Vallecillo', 'departmentIdFK' => 8],
                ['name' => 'Puerto Lempira', 'departmentIdFK' => 9],
                ['name' => 'Brus Laguna', 'departmentIdFK' => 9],
                ['name' => 'Ahuas', 'departmentIdFK' => 9],
                ['name' => 'Juan Francisco  Bulnes', 'departmentIdFK' => 9],
                ['name' => 'Ramón Villeda Morales', 'departmentIdFK' => 9],
                ['name' => 'Wampusirpi', 'departmentIdFK' => 9],
                ['name' => 'La Esperanza', 'departmentIdFK' => 10],
                ['name' => 'Camasca', 'departmentIdFK' => 10],
                ['name' => 'Colomoncagua', 'departmentIdFK' => 10],
                ['name' => 'Concepcion', 'departmentIdFK' => 10],
                ['name' => 'Dolores', 'departmentIdFK' => 10],
                ['name' => 'Intibuca', 'departmentIdFK' => 10],
                ['name' => 'Jesus de Otoro', 'departmentIdFK' => 10],
                ['name' => 'Magdalena', 'departmentIdFK' => 10],
                ['name' => 'Masaguara', 'departmentIdFK' => 10],
                ['name' => 'San Antonio', 'departmentIdFK' => 10],
                ['name' => 'San Isidro', 'departmentIdFK' => 10],
                ['name' => 'San Juan', 'departmentIdFK' => 10],
                ['name' => 'San Marcos de Sierra', 'departmentIdFK' => 10],
                ['name' => 'San Miguelito', 'departmentIdFK' => 10],
                ['name' => 'Santa Lucia', 'departmentIdFK' => 10],
                ['name' => 'Yamaranguila', 'departmentIdFK' => 10],
                ['name' => 'San Francisco de Opalaca', 'departmentIdFK' => 10],
                ['name' => 'Roatan', 'departmentIdFK' => 11],
                ['name' => 'Guanaja', 'departmentIdFK' => 11],
                ['name' => 'Jose Santos Guardiola', 'departmentIdFK' => 11],
                ['name' => 'Utila', 'departmentIdFK' => 11],
                ['name' => 'La Paz', 'departmentIdFK' => 12],
                ['name' => 'Aguanqueterique', 'departmentIdFK' => 12],
                ['name' => 'Cabanas', 'departmentIdFK' => 12],
                ['name' => 'Cane', 'departmentIdFK' => 12],
                ['name' => 'Chinacla', 'departmentIdFK' => 12],
                ['name' => 'Guajiquiro', 'departmentIdFK' => 12],
                ['name' => 'Lauterique', 'departmentIdFK' => 12],
                ['name' => 'Marcala', 'departmentIdFK' => 12],
                ['name' => 'Mercedes de Oriente', 'departmentIdFK' => 12],
                ['name' => 'Opatoro', 'departmentIdFK' => 12],
                ['name' => 'San Antonio del Norte', 'departmentIdFK' => 12],
                ['name' => 'San Jose', 'departmentIdFK' => 12],
                ['name' => 'San Juan', 'departmentIdFK' => 12],
                ['name' => 'San Pedro de Tutule', 'departmentIdFK' => 12],
                ['name' => 'Santa Ana', 'departmentIdFK' => 12],
                ['name' => 'Santa Elena', 'departmentIdFK' => 12],
                ['name' => 'Santa Maria', 'departmentIdFK' => 12],
                ['name' => 'Santiago de Puringla', 'departmentIdFK' => 12],
                ['name' => 'Yarula', 'departmentIdFK' => 12],
                ['name' => 'Gracias', 'departmentIdFK' => 13],
                ['name' => 'Belen', 'departmentIdFK' => 13],
                ['name' => 'Candelaria', 'departmentIdFK' => 13],
                ['name' => 'Cololaca', 'departmentIdFK' => 13],
                ['name' => 'Erandique', 'departmentIdFK' => 13],
                ['name' => 'Gualcince', 'departmentIdFK' => 13],
                ['name' => 'Guarita', 'departmentIdFK' => 13],
                ['name' => 'La Campa', 'departmentIdFK' => 13],
                ['name' => 'La Iguala', 'departmentIdFK' => 13],
                ['name' => 'Las Flores', 'departmentIdFK' => 13],
                ['name' => 'La Union', 'departmentIdFK' => 13],
                ['name' => 'La Virtud', 'departmentIdFK' => 13],
                ['name' => 'Lepaera', 'departmentIdFK' => 13],
                ['name' => 'Mapulaca', 'departmentIdFK' => 13],
                ['name' => 'Piraera', 'departmentIdFK' => 13],
                ['name' => 'San Andres', 'departmentIdFK' => 13],
                ['name' => 'San Francisco', 'departmentIdFK' => 13],
                ['name' => 'San Juan Guarita', 'departmentIdFK' => 13],
                ['name' => 'San Manuel Colohete', 'departmentIdFK' => 13],
                ['name' => 'San Rafael', 'departmentIdFK' => 13],
                ['name' => 'San Sebastian', 'departmentIdFK' => 13],
                ['name' => 'Santa Cruz', 'departmentIdFK' => 13],
                ['name' => 'Talgua', 'departmentIdFK' => 13],
                ['name' => 'Tambla', 'departmentIdFK' => 13],
                ['name' => 'Tomala', 'departmentIdFK' => 13],
                ['name' => 'Valladolid', 'departmentIdFK' => 13],
                ['name' => 'Virginia', 'departmentIdFK' => 13],
                ['name' => 'San Marcos de Caiquin', 'departmentIdFK' => 13],
                ['name' => 'Ocotepeque', 'departmentIdFK' => 14],
                ['name' => 'Belen Gualcho', 'departmentIdFK' => 14],
                ['name' => 'Concepcion', 'departmentIdFK' => 14],
                ['name' => 'Dolores Merendon', 'departmentIdFK' => 14],
                ['name' => 'Fraternidad', 'departmentIdFK' => 14],
                ['name' => 'La Encarnacion', 'departmentIdFK' => 14],
                ['name' => 'La Labor', 'departmentIdFK' => 14],
                ['name' => 'Lucerna', 'departmentIdFK' => 14],
                ['name' => 'Mercedes', 'departmentIdFK' => 14],
                ['name' => 'San Fernando', 'departmentIdFK' => 14],
                ['name' => 'San Francisco del Valle', 'departmentIdFK' => 14],
                ['name' => 'San Jorge', 'departmentIdFK' => 14],
                ['name' => 'San Marcos', 'departmentIdFK' => 14],
                ['name' => 'Santa Fe', 'departmentIdFK' => 14],
                ['name' => 'Sensenti', 'departmentIdFK' => 14],
                ['name' => 'Sinuapa', 'departmentIdFK' => 14],
                ['name' => 'Juticalpa', 'departmentIdFK' => 15],
                ['name' => 'Campamento', 'departmentIdFK' => 15],
                ['name' => 'Catacamas', 'departmentIdFK' => 15],
                ['name' => 'Concordia', 'departmentIdFK' => 15],
                ['name' => 'Dulce Nombre de Culmi', 'departmentIdFK' => 15],
                ['name' => 'El Rosario', 'departmentIdFK' => 15],
                ['name' => 'Esquipulas del Norte', 'departmentIdFK' => 15],
                ['name' => 'Gualaco', 'departmentIdFK' => 15],
                ['name' => 'Guarizama', 'departmentIdFK' => 15],
                ['name' => 'Guata', 'departmentIdFK' => 15],
                ['name' => 'Guayape', 'departmentIdFK' => 15],
                ['name' => 'Jano', 'departmentIdFK' => 15],
                ['name' => 'La Union', 'departmentIdFK' => 15],
                ['name' => 'Mangulile', 'departmentIdFK' => 15],
                ['name' => 'Manto', 'departmentIdFK' => 15],
                ['name' => 'Salama', 'departmentIdFK' => 15],
                ['name' => 'San Esteban', 'departmentIdFK' => 15],
                ['name' => 'San Francisco de Becerra', 'departmentIdFK' => 15],
                ['name' => 'San Francisco de La Paz', 'departmentIdFK' => 15],
                ['name' => 'Santa Maria del Real', 'departmentIdFK' => 15],
                ['name' => 'Silca', 'departmentIdFK' => 15],
                ['name' => 'Yocon', 'departmentIdFK' => 15],
                ['name' => 'Patuca', 'departmentIdFK' => 15],
                ['name' => 'Santa Barbara', 'departmentIdFK' => 16],
                ['name' => 'Arada', 'departmentIdFK' => 16],
                ['name' => 'Atima', 'departmentIdFK' => 16],
                ['name' => 'Azacualpa', 'departmentIdFK' => 16],
                ['name' => 'Ceguaca', 'departmentIdFK' => 16],
                ['name' => 'Concepcion del Norte', 'departmentIdFK' => 16],
                ['name' => 'Concepcion del Sur', 'departmentIdFK' => 16],
                ['name' => 'Chinda', 'departmentIdFK' => 16],
                ['name' => 'El Nispero', 'departmentIdFK' => 16],
                ['name' => 'Gualala', 'departmentIdFK' => 16],
                ['name' => 'Ilama', 'departmentIdFK' => 16],
                ['name' => 'Macuelizo', 'departmentIdFK' => 16],
                ['name' => 'Naranjito', 'departmentIdFK' => 16],
                ['name' => 'Nuevo Celilac', 'departmentIdFK' => 16],
                ['name' => 'Petoa', 'departmentIdFK' => 16],
                ['name' => 'Proteccion', 'departmentIdFK' => 16],
                ['name' => 'Quimistan', 'departmentIdFK' => 16],
                ['name' => 'San Francisco de Ojuera', 'departmentIdFK' => 16],
                ['name' => 'San Jose de Colinas', 'departmentIdFK' => 16],
                ['name' => 'San Luis', 'departmentIdFK' => 16],
                ['name' => 'San Marcos', 'departmentIdFK' => 16],
                ['name' => 'San Nicolas', 'departmentIdFK' => 16],
                ['name' => 'San Pedro Zacapa', 'departmentIdFK' => 16],
                ['name' => 'San Vicente Centenario', 'departmentIdFK' => 16],
                ['name' => 'Santa Rita', 'departmentIdFK' => 16],
                ['name' => 'Trinidad', 'departmentIdFK' => 16],
                ['name' => 'Las Vegas', 'departmentIdFK' => 16],
                ['name' => 'Nueva Frontera', 'departmentIdFK' => 16],
                ['name' => 'Nacaome', 'departmentIdFK' => 17],
                ['name' => 'Alianza', 'departmentIdFK' => 17],
                ['name' => 'Amapala', 'departmentIdFK' => 17],
                ['name' => 'Aramecina', 'departmentIdFK' => 17],
                ['name' => 'Caridad', 'departmentIdFK' => 17],
                ['name' => 'Goascoran', 'departmentIdFK' => 17],
                ['name' => 'Langue', 'departmentIdFK' => 17],
                ['name' => 'San Francisco de Coray', 'departmentIdFK' => 17],
                ['name' => 'San Lorenzo', 'departmentIdFK' => 17],
                ['name' => 'Yoro', 'departmentIdFK' => 18],
                ['name' => 'Arenal', 'departmentIdFK' => 18],
                ['name' => 'El Negrito', 'departmentIdFK' => 18],
                ['name' => 'El Progreso', 'departmentIdFK' => 18],
                ['name' => 'Jocon', 'departmentIdFK' => 18],
                ['name' => 'Morazan', 'departmentIdFK' => 18],
                ['name' => 'Olanchito', 'departmentIdFK' => 18],
                ['name' => 'Santa Rita', 'departmentIdFK' => 18],
                ['name' => 'Sulaco', 'departmentIdFK' => 18],
                ['name' => 'Victoria', 'departmentIdFK' => 18],
                ['name' => 'Yorito', 'departmentIdFK' => 18]
            ]
        );


    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('municipalities');
    }
};
